"""initial

Revision ID: 0e0b66541128
Revises: 
Create Date: 2026-06-11 16:16:07.221524

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0e0b66541128'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bank_names',
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uuid', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('uuid')
    )
    op.create_index(op.f('ix_bank_names_id'), 'bank_names', ['id'], unique=False)
    op.create_table('brand_names',
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uuid', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('uuid')
    )
    op.create_index(op.f('ix_brand_names_id'), 'brand_names', ['id'], unique=False)
    op.create_table('users',
    sa.Column('full_name', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('password_hash', sa.String(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('birthdate', sa.Date(), nullable=False),
    sa.Column('cpf', sa.String(), nullable=False),
    sa.Column('phone_number', sa.String(), nullable=False),
    sa.Column('is_2fa_enabled', sa.Boolean(), nullable=True),
    sa.Column('two_factor_secret', sa.String(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uuid', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('uuid')
    )
    op.create_index(op.f('ix_users_cpf'), 'users', ['cpf'], unique=True)
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_index(op.f('ix_users_phone_number'), 'users', ['phone_number'], unique=True)
    op.create_table('category_transactions',
    sa.Column('id_user', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uuid', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['id_user'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('uuid')
    )
    op.create_index(op.f('ix_category_transactions_id'), 'category_transactions', ['id'], unique=False)
    op.create_table('financial_accounts',
    sa.Column('id_user', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('account_type', sa.Enum('CURRENT_ACCOUNT', 'SAVINGS_ACCOUNT', 'SALARY_ACCOUNT', 'INVESTMENT_ACCOUNT', name='accounttypeenum'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('id_bank_name', sa.Integer(), nullable=True),
    sa.Column('is_primary_bank', sa.Boolean(), nullable=False),
    sa.Column('overdraft_limit', sa.Float(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uuid', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['id_bank_name'], ['bank_names.id'], ),
    sa.ForeignKeyConstraint(['id_user'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('uuid')
    )
    op.create_index(op.f('ix_financial_accounts_id'), 'financial_accounts', ['id'], unique=False)
    op.create_table('loan_recipients',
    sa.Column('id_user', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uuid', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['id_user'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id_user', 'name', name='uq_loan_recipients_user_name'),
    sa.UniqueConstraint('uuid')
    )
    op.create_index(op.f('ix_loan_recipients_id'), 'loan_recipients', ['id'], unique=False)
    op.create_table('merchant_names',
    sa.Column('id_user', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uuid', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['id_user'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id_user', 'name', name='uq_merchant_names_user_name'),
    sa.UniqueConstraint('uuid')
    )
    op.create_index(op.f('ix_merchant_names_id'), 'merchant_names', ['id'], unique=False)
    op.create_table('account_transactions',
    sa.Column('id_user', sa.Integer(), nullable=False),
    sa.Column('id_financial_account', sa.Integer(), nullable=False),
    sa.Column('id_category_transaction', sa.Integer(), nullable=False),
    sa.Column('id_merchant_name', sa.Integer(), nullable=True),
    sa.Column('id_loan_recipient', sa.Integer(), nullable=True),
    sa.Column('transaction_type', sa.Enum('income', 'expense', name='transaction_type_enum'), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('purchase_date', sa.Date(), nullable=False),
    sa.Column('payment_date', sa.Date(), nullable=False),
    sa.Column('value', sa.Float(), nullable=False),
    sa.Column('is_paid', sa.Boolean(), nullable=True),
    sa.Column('is_recurring', sa.Boolean(), nullable=False),
    sa.Column('recurrence_frequency', sa.Enum('DAILY', 'WEEKLY', 'BIWEEKLY', 'MONTHLY', 'BIMONTHLY', 'QUARTERLY', 'SEMIANNUAL', 'ANNUAL', name='recurrence_frequency_enum'), nullable=True),
    sa.Column('recurrence_enabled', sa.Boolean(), nullable=False),
    sa.Column('recurrence_group_id', sa.UUID(), nullable=True),
    sa.Column('recurrence_parent_id', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uuid', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['id_category_transaction'], ['category_transactions.id'], ),
    sa.ForeignKeyConstraint(['id_financial_account'], ['financial_accounts.id'], ),
    sa.ForeignKeyConstraint(['id_loan_recipient'], ['loan_recipients.id'], ),
    sa.ForeignKeyConstraint(['id_merchant_name'], ['merchant_names.id'], ),
    sa.ForeignKeyConstraint(['id_user'], ['users.id'], ),
    sa.ForeignKeyConstraint(['recurrence_parent_id'], ['account_transactions.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('uuid')
    )
    op.create_index(op.f('ix_account_transactions_id'), 'account_transactions', ['id'], unique=False)
    op.create_table('account_transfers',
    sa.Column('id_user', sa.Integer(), nullable=False),
    sa.Column('id_origin_account', sa.Integer(), nullable=False),
    sa.Column('id_destination_account', sa.Integer(), nullable=False),
    sa.Column('transfer_date', sa.Date(), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uuid', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['id_destination_account'], ['financial_accounts.id'], ),
    sa.ForeignKeyConstraint(['id_origin_account'], ['financial_accounts.id'], ),
    sa.ForeignKeyConstraint(['id_user'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('uuid')
    )
    op.create_index(op.f('ix_account_transfers_id'), 'account_transfers', ['id'], unique=False)
    op.create_table('cards',
    sa.Column('id_user', sa.Integer(), nullable=False),
    sa.Column('id_account', sa.Integer(), nullable=True),
    sa.Column('id_brand_names', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('card_type', sa.Enum('CREDIT_CARD', 'PREPAID_CARD', name='cardtypeenum'), nullable=False),
    sa.Column('due_day', sa.Integer(), nullable=False),
    sa.Column('closing_day', sa.Integer(), nullable=True),
    sa.Column('limit', sa.Float(), nullable=True),
    sa.Column('last_4_digits', sa.String(length=4), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uuid', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['id_account'], ['financial_accounts.id'], ),
    sa.ForeignKeyConstraint(['id_brand_names'], ['brand_names.id'], ),
    sa.ForeignKeyConstraint(['id_user'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('uuid')
    )
    op.create_index(op.f('ix_cards_id'), 'cards', ['id'], unique=False)
    op.create_table('account_transaction_installments',
    sa.Column('id_account_transaction', sa.Integer(), nullable=False),
    sa.Column('installment_number', sa.Integer(), nullable=False),
    sa.Column('due_date', sa.Date(), nullable=False),
    sa.Column('value', sa.Float(), nullable=False),
    sa.Column('is_paid', sa.Boolean(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uuid', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['id_account_transaction'], ['account_transactions.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('uuid')
    )
    op.create_index(op.f('ix_account_transaction_installments_id'), 'account_transaction_installments', ['id'], unique=False)
    op.create_table('card_invoices',
    sa.Column('id_user', sa.Integer(), nullable=False),
    sa.Column('id_card', sa.Integer(), nullable=False),
    sa.Column('id_account_transaction', sa.Integer(), nullable=True),
    sa.Column('reference_month', sa.Date(), nullable=False),
    sa.Column('closing_date', sa.Date(), nullable=False),
    sa.Column('due_date', sa.Date(), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=False),
    sa.Column('total_amount', sa.Float(), nullable=True),
    sa.Column('paid_amount', sa.Float(), nullable=True),
    sa.Column('status', sa.Enum('OPEN', 'CLOSED', 'PAID', 'OVERDUE', name='cardinvoicestatusenum'), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uuid', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['id_account_transaction'], ['account_transactions.id'], ),
    sa.ForeignKeyConstraint(['id_card'], ['cards.id'], ),
    sa.ForeignKeyConstraint(['id_user'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('uuid')
    )
    op.create_index(op.f('ix_card_invoices_id'), 'card_invoices', ['id'], unique=False)
    op.create_table('card_transactions',
    sa.Column('id_user', sa.Integer(), nullable=False),
    sa.Column('id_card', sa.Integer(), nullable=False),
    sa.Column('id_category_transaction', sa.Integer(), nullable=False),
    sa.Column('id_merchant_name', sa.Integer(), nullable=True),
    sa.Column('id_loan_recipient', sa.Integer(), nullable=True),
    sa.Column('transaction_type', sa.Enum('income', 'expense', name='transaction_type_enum'), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('purchase_date', sa.Date(), nullable=False),
    sa.Column('total_value', sa.Float(), nullable=False),
    sa.Column('installments_count', sa.Integer(), nullable=True),
    sa.Column('is_canceled', sa.Boolean(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uuid', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['id_card'], ['cards.id'], ),
    sa.ForeignKeyConstraint(['id_category_transaction'], ['category_transactions.id'], ),
    sa.ForeignKeyConstraint(['id_loan_recipient'], ['loan_recipients.id'], ),
    sa.ForeignKeyConstraint(['id_merchant_name'], ['merchant_names.id'], ),
    sa.ForeignKeyConstraint(['id_user'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('uuid')
    )
    op.create_index(op.f('ix_card_transactions_id'), 'card_transactions', ['id'], unique=False)
    op.create_table('card_transaction_installments',
    sa.Column('id_card_transaction', sa.Integer(), nullable=False),
    sa.Column('id_card_invoice', sa.Integer(), nullable=False),
    sa.Column('installment_number', sa.Integer(), nullable=False),
    sa.Column('value', sa.Float(), nullable=False),
    sa.Column('due_date', sa.Date(), nullable=False),
    sa.Column('is_paid', sa.Boolean(), nullable=True),
    sa.Column('paid_at', sa.Date(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uuid', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['id_card_invoice'], ['card_invoices.id'], ),
    sa.ForeignKeyConstraint(['id_card_transaction'], ['card_transactions.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('uuid')
    )
    op.create_index(op.f('ix_card_transaction_installments_id'), 'card_transaction_installments', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_card_transaction_installments_id'), table_name='card_transaction_installments')
    op.drop_table('card_transaction_installments')
    op.drop_index(op.f('ix_card_transactions_id'), table_name='card_transactions')
    op.drop_table('card_transactions')
    op.drop_index(op.f('ix_card_invoices_id'), table_name='card_invoices')
    op.drop_table('card_invoices')
    op.drop_index(op.f('ix_account_transaction_installments_id'), table_name='account_transaction_installments')
    op.drop_table('account_transaction_installments')
    op.drop_index(op.f('ix_cards_id'), table_name='cards')
    op.drop_table('cards')
    op.drop_index(op.f('ix_account_transfers_id'), table_name='account_transfers')
    op.drop_table('account_transfers')
    op.drop_index(op.f('ix_account_transactions_id'), table_name='account_transactions')
    op.drop_table('account_transactions')
    op.drop_index(op.f('ix_merchant_names_id'), table_name='merchant_names')
    op.drop_table('merchant_names')
    op.drop_index(op.f('ix_loan_recipients_id'), table_name='loan_recipients')
    op.drop_table('loan_recipients')
    op.drop_index(op.f('ix_financial_accounts_id'), table_name='financial_accounts')
    op.drop_table('financial_accounts')
    op.drop_index(op.f('ix_category_transactions_id'), table_name='category_transactions')
    op.drop_table('category_transactions')
    op.drop_index(op.f('ix_users_phone_number'), table_name='users')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_index(op.f('ix_users_cpf'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_brand_names_id'), table_name='brand_names')
    op.drop_table('brand_names')
    op.drop_index(op.f('ix_bank_names_id'), table_name='bank_names')
    op.drop_table('bank_names')
    # ### end Alembic commands ###
