"""update transaction type enum

Revision ID: 48e00ee07fb4
Revises: 4e7039c30a51
Create Date: 2026-06-12 22:01:10.303450

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "48e00ee07fb4"
down_revision: Union[str, Sequence[str], None] = "4e7039c30a51"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    op.execute("""
        ALTER TYPE transaction_type_enum
        ADD VALUE IF NOT EXISTS 'transfer';
    """)


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
