"""update table category transaction

Revision ID: 4e7039c30a51
Revises: 0e0b66541128
Create Date: 2026-06-11 17:59:30.250395

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4e7039c30a51'
down_revision: Union[str, Sequence[str], None] = '0e0b66541128'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('category_transactions', sa.Column('description', sa.String(), nullable=True))
    op.add_column('category_transactions', sa.Column('type', sa.Enum('income', 'expense', name='transaction_type_enum'), nullable=False))
    op.alter_column('category_transactions', 'id_user',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('category_transactions', 'id_user',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_column('category_transactions', 'type')
    op.drop_column('category_transactions', 'description')
    # ### end Alembic commands ###
